resources:
  - name: repo
    type: git
    source: 
      uri: https://github.com/anjipunsi/vault.git
      branch: main

jobs:
  - name: run-python-script
    plan:
      - get: repo
        trigger: true

      - task: run-python-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: python
              tag: "3.9"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                # Install required libraries
                pip install bs4 
                pip install pandas
                pip install requests
                pip install mysql-connector-python
                pip install SQLAlchemy 
                ls -l
                cd repo
                ls - l
                python reliance.py
